### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by leftclickben**

### CODE REVIEW

**Comment by kehh** [comment]
Those tests don't appear to be failing upstream - https://travis-ci.org/collectiveaccess/providence/branches. Is there a problem with locales or something similar?

**Comment by leftclickben** [comment]
I'm going to disable the tests, because that's what you do with tests that fail...

**Comment by leftclickben** [comment]
Excluded tests that call an external service.  They are too flaky and we aren't using the external services anyway.

**Comment by leftclickben** [comment]
Closed in favour of #10

**Pull request closed without merging**
